defaults:
- override: 'hydra/launcher: basic'
metadata:
  description: Example hyperparameter sweep
  tags:
  - example
  - baseline
sweep:
  grid:
    batch_size:
    - 32
    - 64
    learning_rate:
    - 0.001
    - 0.01
    - 0.1
    seed:
    - 1
    - 2
    - 3
    - 4
    - 5
