compute:
  default_timeout: null
  health_check_interval: 300
  max_concurrent_local: 1
  max_concurrent_remote: 10
  result_collection_interval: 60
  retry_attempts: 3
  retry_delay: 60
experiment_tracking:
  mlflow_enabled: false
  mlflow_tracking_uri: null
  tensorboard_enabled: false
  wandb_enabled: false
  wandb_entity: null
  wandb_project: null
hpc:
  default_queue: null
  default_resources: select=1:ncpus=4:mem=64gb
  default_walltime: '23:59:59'
  max_array_size: null
  module_commands: []
  system: local
logging:
  backup_count: 5
  console_logging: true
  file_logging: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_log_size: 100MB
paths:
  conda_env: nca
  project_root: /home/gb21/code/HPC-Sweep-Manager/examples/simple_mlp
  python_interpreter: /home/gb21/miniconda3/envs/nca/bin/python
  training_script: /home/gb21/code/HPC-Sweep-Manager/examples/simple_mlp/main.py
